import { DIFFICULTY_EASY, DIFFICULTY_EXPERT, DIFFICULTY_HARD, DIFFICULTY_MASTER, DIFFICULTY_MEDIUM } from "sudoku-core/dist/cjs/constants";

export const DIFFICULTIES = [
    DIFFICULTY_EASY,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_HARD,
    DIFFICULTY_EXPERT,
    DIFFICULTY_MASTER
] as const;
